default: &default
adapter: postgresql
encoding: SQL_ASCII
host: localhost
pool: 5
username: ubuntu
password: jlpeter68

development:
<<: *default
database: app_development

test:
<<: *default
database: app_test

production:
<<: *default
database: app_production
